apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: live-platform
resources:
  # - ../../base
  - sealed-runtime.yaml

images:
  - name: live-platform
    newName: ghcr.io/fff-rick/live-platform
    newTag: v1.0
